Merge actions-implementation into cobra-migration
RareBeeph/golang-practice-cat pull request #2
Opened 2022-11-08 03:09 UTC by RareBeeph

2022-11-09 23:01 UTC, aricodes-oss requested changes
One major issue, one minor issue, and one nitpick - name your PRs better. A good PR title is a good commit message, and is what your commits will be squashed under when we merge them.

2022-11-09 23:01 UTC, aricodes-oss commented on .github/workflows/test-action.yml
> +      - run: go test -v ./cmd
Just for future proofing, the command `go test ./...` will run all tests from the current package and sub packages. That way this won't need to be updated for future test suites.

2022-11-09 23:01 UTC, aricodes-oss commented on .github/workflows/test-action.yml
> +          ref: 'actions-implementation'
Nope. That prevents this from running on any other branch than this one, remove that qualifier. GA is pretty smart and knows what you mean when you ask it to checkout the repo

2022-11-10 00:51 UTC, ariataylor96 requested changes

2022-11-10 00:51 UTC, ariataylor96 commented on cmd/root_test.go
> +	var testExitCode int
The "dead man's switch" concept here is a clever pattern for solving tricky control flow problems, but is a bit too manual. Your test suite code should be treated as a library being run by the testing framework - in this case, the `T` context object you receive from the framework has a method called `Fail()` that you can use to mark a test as failed, removing the need for this mechanism.

2022-11-10 01:37 UTC, ariataylor96 approved these changes

2022-11-10 01:40 UTC, merged